add the first Social Smell, SPRIOO2 which check if the app import goo…
green-code-initiative/ecoCode-mobile pull request #21
Opened 2023-02-01 13:27 UTC by Jberque

add the first Social Smell, SPRIOO2 which check if the app import google analytics or firebase analytics

refactor project including social package, and adding Energy package for energy rules

2023-02-02 10:26 UTC, olegoaer requested changes
The academic citation cannot be changed. It is linked to an immutable official DOI
https://dl.acm.org/doi/abs/10.1145/3551349.3559518

2023-02-09 08:35 UTC, olegoaer approved these changes

2023-02-13 15:15 UTC, jhertout commented on android-plugin/src/test/files/social/privacy/GoogleTrackerCheck.java
> +import com.google.android.gms.analytics.Tracker; // Noncompliant {{Using com.google.android.gms.analytics.* is a potential threat for privacy.}}
We should test more imports cases : 

- import com.google.android.gms.analytics.*
- import com.google.android.gms.Test
- import com.google.android.gms.analytics.UneAutreClasse
- import com.io.ecocode.MaClasse

2023-02-13 15:15 UTC, jhertout commented on android-plugin/src/test/files/social/privacy/GoogleTrackerGoogleAndFirebaseCheck.java
> +import com.google.firebase.analytics.FirebaseAnalytics; // Noncompliant {{Using com.google.firebase.analytics.* is a potential threat for privacy.}}
Same as other test class, we should test more cases.

2023-02-13 15:15 UTC, jhertout commented on android-plugin/src/main/resources/org/sonar/l10n/java/rules/squid/SPRI002_java.html
> +    Importing the <code>com.google.android.gms.analytics.Tracker</code> class means that the app sends hits to Google Analytics. It is not necessarily sensitive information, but it is a first step to
Why do we not talk about "import com.google.firebase.analytics" in this paragraph?

2023-02-13 15:15 UTC, jhertout commented on android-plugin/src/main/java/io/ecocode/java/checks/social/GoogleTrackerRule.java
> +            googleTrackerImport.allAnalyticsImport.addAll(googleTrackerImport.getFirebaseTrackerImports());
Can we have a getter in GoogleTrackerImports  that directly returns the combined list?

2023-02-13 15:15 UTC, jhertout commented on android-plugin/src/main/java/io/ecocode/java/checks/social/GoogleTrackerRule.java
> +        public ImportTree getTree() {
This getter is not used. Access is done directly on variable. Why not but in this case delete the getter.

2023-02-13 15:15 UTC, jhertout commented on android-plugin/src/main/java/io/ecocode/java/checks/social/GoogleTrackerRule.java
> +        public String getDesc() {
Same comment as getTree()

2023-02-13 15:15 UTC, jhertout commented on android-plugin/src/main/java/io/ecocode/java/checks/social/GoogleTrackerRule.java
> +    public static class AnalyticsIssue {
Why public static? I think private is enough.

2023-02-13 15:15 UTC, jhertout commented on android-plugin/src/main/java/io/ecocode/java/checks/social/GoogleTrackerRule.java
> +    private static class GoogleTrackerImports {
Why public static? I think private is enough.

2023-02-13 15:15 UTC, jhertout commented on android-plugin/src/main/java/io/ecocode/java/checks/social/GoogleTrackerRule.java
> +        private static final String IMPORT_STR_GGL_TRCK = "com.google.android.gms.analytics";
IMPORT_STR_GGL_TRCK  -> Can we use full word instead of abreviation for clarity? (same for other static and not static variables)

2023-02-13 15:16 UTC, jhertout commented on android-plugin/src/main/java/io/ecocode/java/checks/social/GoogleTrackerRule.java
> +        private static final String IMPORT_STR_GGL_TRCK = "com.google.android.gms.analytics";
There is a Sonar "bug" detected @Jberque. i don't think it was added because of your MR but can you fix it?

2023-02-21 16:01 UTC, merged